/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SecretRaffleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getMyResult"
      | "isGameReady"
      | "owner"
      | "protocolId"
      | "submitGuess"
      | "userGuessResults"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "GuessSubmitted" | "SecretNumberInitialized"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getMyResult",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isGameReady",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitGuess",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userGuessResults",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getMyResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isGameReady",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitGuess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userGuessResults",
    data: BytesLike
  ): Result;
}

export namespace GuessSubmittedEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SecretNumberInitializedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SecretRaffle extends BaseContract {
  connect(runner?: ContractRunner | null): SecretRaffle;
  waitForDeployment(): Promise<this>;

  interface: SecretRaffleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getMyResult: TypedContractMethod<[user: AddressLike], [string], "view">;

  isGameReady: TypedContractMethod<[], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  submitGuess: TypedContractMethod<
    [encryptedGuess: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  userGuessResults: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getMyResult"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "isGameReady"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitGuess"
  ): TypedContractMethod<
    [encryptedGuess: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userGuessResults"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getEvent(
    key: "GuessSubmitted"
  ): TypedContractEvent<
    GuessSubmittedEvent.InputTuple,
    GuessSubmittedEvent.OutputTuple,
    GuessSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "SecretNumberInitialized"
  ): TypedContractEvent<
    SecretNumberInitializedEvent.InputTuple,
    SecretNumberInitializedEvent.OutputTuple,
    SecretNumberInitializedEvent.OutputObject
  >;

  filters: {
    "GuessSubmitted(address)": TypedContractEvent<
      GuessSubmittedEvent.InputTuple,
      GuessSubmittedEvent.OutputTuple,
      GuessSubmittedEvent.OutputObject
    >;
    GuessSubmitted: TypedContractEvent<
      GuessSubmittedEvent.InputTuple,
      GuessSubmittedEvent.OutputTuple,
      GuessSubmittedEvent.OutputObject
    >;

    "SecretNumberInitialized()": TypedContractEvent<
      SecretNumberInitializedEvent.InputTuple,
      SecretNumberInitializedEvent.OutputTuple,
      SecretNumberInitializedEvent.OutputObject
    >;
    SecretNumberInitialized: TypedContractEvent<
      SecretNumberInitializedEvent.InputTuple,
      SecretNumberInitializedEvent.OutputTuple,
      SecretNumberInitializedEvent.OutputObject
    >;
  };
}
